version: "3.3"

services:

  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: miniautorizador
      MYSQL_ROOT_PASSWORD: root